feature: Add GoSec support

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -57,6 +57,16 @@ inputs:
     description: >-
       Reduce issue severity by one level, for non-security issues, for compatibility with GitHub's code scanning feature.
       This option will only have an effect when used in conjunction with '--format sarif'.
+  run-docker-tools:
+    required: false
+    default: "true"
+    description: >-
+      Run dockerized tools. Possible values (true|false)
+      Check the full list in https://docs.codacy.com/repositories-configure/codacy-configuration-file/#which-tools-can-be-configured-and-which-name-should-i-use
+  run-gosec:
+    required: false
+    description: >-
+      Run GoSec. Possible values (true|false)
 runs:
   using: "composite"
   steps:
@@ -66,13 +76,44 @@ runs:
         echo "OWNER_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)" >> $GITHUB_ENV
         echo "REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV
         echo "ORGANIZATION_PROVIDER=$(if [ "$GITHUB_SERVER_URL" == "https://github.com" ]; then echo "gh"; else echo "ghe"; fi)" >> $GITHUB_ENV
+
+    - name: "Prepare curl authentication header"
+      shell: bash
+      run: |
+        if [ -n "${{ inputs.api-token }}" ]; then
+          echo "CURL_CODACY_AUTH_AUTHENTICATION=api-token: ${{ inputs.api-token }}" >> $GITHUB_ENV
+        else
+          echo "CURL_CODACY_AUTH_AUTHENTICATION=project-token: ${{ inputs.project-token }}" >> $GITHUB_ENV
+        fi
+
+    - name: "Run GoSec"
+      shell: bash
+      run: |
+        set -eux
+
+        if [ "${{ inputs.run-gosec }}" == "true" ]; then
+          cd /tmp
+          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.7.0
+          chmod +x ./bin/gosec
+          curl -fsSL https://api.github.com/repos/codacy/codacy-gosec/releases/latest \
+            | grep "browser_download_url" | grep -v "browser_download_url.*jar" \
+            | cut -d '"' -f 4 \
+            | xargs -L 1 curl -fsSL -o /tmp/bin/codacy-gosec
+          chmod +x ./bin/codacy-gosec
+          cd -
+
+          /tmp/bin/gosec -no-fail -fmt json -log log.txt ./... > gosec-out.json
+          /tmp/bin/codacy-gosec < gosec-out.json > codacy-out.json
+          curl -XPOST -L -H "$CURL_CODACY_AUTH_AUTHENTICATION" \
+            -H "Content-type: application/json" --data-binary @codacy-out.json \
+            "https://api.codacy.com/2.0/$ORGANIZATION_PROVIDER/$OWNER_NAME/$REPOSITORY_NAME/commit/$GITHUB_SHA/issuesRemoteResults"
+        else
+          echo "Skipping GoSec"
+        fi
+
     - name: "Set Codacy CLI version"
       shell: bash
-<<<<<<< HEAD
       run: echo "CODACY_ANALYSIS_CLI_VERSION=6.2.1" >> $GITHUB_ENV
-=======
-      run: echo "CODACY_ANALYSIS_CLI_VERSION=6.2.0" >> $GITHUB_ENV
->>>>>>> c22a36c (bump: Update cli version)
     - name: "Set script path environment variable"
       shell: bash
       run: echo "CLI_SCRIPT_PATH=${{ github.action_path }}/codacy-analysis-cli.sh" >> $GITHUB_ENV
@@ -85,21 +126,32 @@ runs:
     - name: "Run Codacy CLI"
       shell: bash
       run: |
-        ${{ env.CLI_SCRIPT_PATH }} \
-          analyze \
-          $(if [ "${{ inputs.verbose }}" = "true" ]; then echo "--verbose"; fi) \
-          $(if [ -n "${{ inputs.project-token }}" ]; then echo "--project-token ${{ inputs.project-token }}"; fi) \
-          $(if [ -n "${{ inputs.api-token }}" ]; then echo "--api-token ${{ inputs.api-token }} --username $OWNER_NAME --project $REPOSITORY_NAME --provider $ORGANIZATION_PROVIDER"; fi) \
-          $(if [ -n "${{ inputs.codacy-api-base-url }}" ]; then echo "--codacy-api-base-url ${{ inputs.codacy-api-base-url }}"; fi) \
-          $(if [ -n "${{ inputs.format }}" ]; then echo "--format ${{ inputs.format }}"; fi) \
-          $(if [ -n "${{ inputs.output }}" ]; then echo "--output ${{ inputs.output }}"; fi) \
-          $(if [ -n "${{ inputs.directory }}" ]; then echo "--directory ${{ inputs.directory }}"; fi) \
-          $(if [ -n "${{ inputs.parallel }}" ]; then echo "--parallel ${{ inputs.parallel }}"; fi) \
-          $(if [ -n "${{ inputs.max-allowed-issues }}" ]; then echo "--max-allowed-issues ${{ inputs.max-allowed-issues }}"; fi) \
-          $(if [ -n "${{ inputs.tool }}" ]; then echo "--tool ${{ inputs.tool }}"; fi) \
-          $(if [ -n "${{ inputs.tool-timeout }}" ]; then echo "--tool-timeout ${{ inputs.tool-timeout }}"; fi) \
-          $(if [ "${{ inputs.upload }}" = "true" ]; then echo "--upload"; fi) \
-          $(if [ "${{ inputs.fail-if-incomplete }}" = "true" ]; then echo "--fail-if-incomplete"; fi) \
-          $(if [ "${{ inputs.allow-network }}" = "true" ]; then echo "--allow-network"; fi) \
-          $(if [ "${{ inputs.force-file-permissions }}" = "true" ]; then echo "--force-file-permissions"; fi) \
-          $(if [ "${{ inputs.gh-code-scanning-compat }}" = "true" ]; then echo "--gh-code-scanning-compat"; fi)
+        if [ "${{ inputs.run-docker-tools }}" == "true" ]; then
+          ${{ env.CLI_SCRIPT_PATH }} \
+            analyze \
+            $(if [ "${{ inputs.verbose }}" = "true" ]; then echo "--verbose"; fi) \
+            $(if [ -n "${{ inputs.project-token }}" ]; then echo "--project-token ${{ inputs.project-token }}"; fi) \
+            $(if [ -n "${{ inputs.api-token }}" ]; then echo "--api-token ${{ inputs.api-token }} --username $OWNER_NAME --project $REPOSITORY_NAME --provider $ORGANIZATION_PROVIDER"; fi) \
+            $(if [ -n "${{ inputs.codacy-api-base-url }}" ]; then echo "--codacy-api-base-url ${{ inputs.codacy-api-base-url }}"; fi) \
+            $(if [ -n "${{ inputs.format }}" ]; then echo "--format ${{ inputs.format }}"; fi) \
+            $(if [ -n "${{ inputs.output }}" ]; then echo "--output ${{ inputs.output }}"; fi) \
+            $(if [ -n "${{ inputs.directory }}" ]; then echo "--directory ${{ inputs.directory }}"; fi) \
+            $(if [ -n "${{ inputs.parallel }}" ]; then echo "--parallel ${{ inputs.parallel }}"; fi) \
+            $(if [ -n "${{ inputs.max-allowed-issues }}" ]; then echo "--max-allowed-issues ${{ inputs.max-allowed-issues }}"; fi) \
+            $(if [ -n "${{ inputs.tool }}" ]; then echo "--tool ${{ inputs.tool }}"; fi) \
+            $(if [ -n "${{ inputs.tool-timeout }}" ]; then echo "--tool-timeout ${{ inputs.tool-timeout }}"; fi) \
+            $(if [ "${{ inputs.upload }}" = "true" ]; then echo "--upload"; fi) \
+            $(if [ "${{ inputs.fail-if-incomplete }}" = "true" ]; then echo "--fail-if-incomplete"; fi) \
+            $(if [ "${{ inputs.allow-network }}" = "true" ]; then echo "--allow-network"; fi) \
+            $(if [ "${{ inputs.force-file-permissions }}" = "true" ]; then echo "--force-file-permissions"; fi) \
+            $(if [ "${{ inputs.gh-code-scanning-compat }}" = "true" ]; then echo "--gh-code-scanning-compat"; fi)
+        else
+          echo "Skipping docker tools"
+        fi
+
+    - name: "Let Codacy know it can start processing the analysis results"
+      shell: bash
+      run: |
+        curl -XPOST -L -H "$CURL_CODACY_AUTH_AUTHENTICATION" \
+          -H "Content-type: application/json" \
+          "https://api.codacy.com/2.0/$ORGANIZATION_PROVIDER/$OWNER_NAME/$REPOSITORY_NAME/commit/$GITHUB_SHA/resultsFinal"
